# Generated by Django 5.0.14 on 2026-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('category', models.CharField(choices=[('python', 'Python Questions'), ('django', 'Django Questions'), ('frontend', 'Frontend Questions'), ('interview', 'Interview Questions')], default='python', max_length=20)),
                ('tags', models.CharField(help_text='Comma-separated values e.g. loops, dynamic-programming', max_length=200)),
                ('problem_statement', models.TextField()),
                ('explanation', models.TextField(help_text='Detailed step-by-step logic breakdown.')),
                ('solution_code', models.TextField(help_text='Solution in Programming Language syntax.')),
                ('sample_output', models.TextField(blank=True, help_text='Console output resulting from executing the code.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
