# Generated by Django 5.0.14 on 2026-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/')),
                ('technologies', models.CharField(help_text='Comma-separated values e.g. Django, Python, PostgreSQL, GSAP', max_length=200)),
                ('short_description', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Full detail case study content. Supports HTML.', null=True)),
                ('live_url', models.URLField(blank=True, help_text='Link to live hosted website.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
