# Generated by Django 5.0.14 on 2026-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='FontAwesome icon class name e.g. fa-solid fa-code', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starting_price', models.CharField(help_text='e.g. ₹15,000 or ₹79/hr', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='Client role or company e.g. CTO at Startup', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/profiles/')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('feedback', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
