# Generated by Django 5.0.14 on 2026-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnails/')),
                ('content_markdown', models.TextField(help_text='Write blog post using markdown syntax.')),
                ('category', models.CharField(choices=[('coding_tips', 'Coding Tips'), ('career_advice', 'Career Advice'), ('python', 'Python'), ('django', 'Django'), ('web_dev', 'Web Development')], default='web_dev', max_length=30)),
                ('tags', models.CharField(help_text='Comma-separated tags e.g. django, server, security', max_length=200)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
