# Generated by Django 5.0.14 on 2026-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('programming_language', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('sql', 'SQL'), ('other', 'Other')], default='other', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('thumbnail', models.ImageField(upload_to='notes/thumbnails/')),
                ('summary', models.TextField(help_text='Short abstract or quick-read notes preview.')),
                ('content_markdown', models.TextField(help_text='Full notes text support Markdown syntax.')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload premium offline notes PDF copy.', null=True, upload_to='notes/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
