# Generated by Django 5.2.8 on 2026-07-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='Rich HTML content. Used if Rich HTML Editor is selected.'),
        ),
        migrations.AddField(
            model_name='note',
            name='content_type',
            field=models.CharField(choices=[('markdown', 'Markdown / Code Editor'), ('html', 'Rich HTML Editor (CKEditor)')], default='markdown', help_text="Choose 'Markdown' for code blocks, or 'Rich HTML Editor' for normal text editing.", max_length=15),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_markdown',
            field=models.TextField(blank=True, default='', help_text='Full notes text support Markdown syntax.'),
        ),
    ]
