# Generated by Django 5.2.8 on 2026-07-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description/overview of this topic. Supports rich HTML (CKEditor).'),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(help_text='SubTopic content in HTML. Supports CKEditor rich editing and code blocks.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the parent topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='learn.topic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
