# Generated by Django 5.2.8 on 2026-07-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_topic_description_subtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.AddField(
            model_name='topic',
            name='content_code',
            field=models.TextField(blank=True, default='', help_text='Topic content in Raw HTML. Used if Raw HTML Code is selected.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_type',
            field=models.CharField(choices=[('editor', 'Rich HTML Editor (CKEditor)'), ('code', 'Raw HTML Code')], default='editor', help_text="Choose 'Rich HTML Editor' for normal text editing, or 'Raw HTML Code' to paste raw HTML.", max_length=15),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Topic content in Rich HTML. Used if Rich HTML Editor is selected.'),
        ),
    ]
