# Generated by Django 5.2.8 on 2026-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_remove_topic_description_topic_content_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='content_code',
            field=models.TextField(blank=True, default='', help_text='SubTopic content in Raw HTML. Used if Raw HTML Code is selected.'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='content_type',
            field=models.CharField(choices=[('editor', 'Rich HTML Editor (CKEditor)'), ('code', 'Raw HTML Code')], default='editor', help_text="Choose 'Rich HTML Editor' for normal text editing, or 'Raw HTML Code' to paste raw HTML.", max_length=15),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=models.TextField(blank=True, default='', help_text='SubTopic content in Rich HTML. Used if Rich HTML Editor is selected.'),
        ),
    ]
